#+TITLE: browse-kill-ring README

* ABOUT

Are you tired of using the endless keystrokes of =C-y M-y M-y M-y ...= to get
at that bit of text you killed thirty-seven kills ago? Ever wish you could just
look through everything you've killed recently to find out if you killed that
piece of text that you think you killed, but you're not quite sure? If so, then
browse-kill-ring.el is the emacs extension for you.

* INSTALLATION

Installation is simple:

- Put =browse-kill-ring.el= somewhere in your emacs =load-path=.
- Next, add the form =(require 'browse-kill-ring)= to your =~/.emacs= file.
- Optionally, you can map =M-y= to =browse-kill-ring= by adding the form
  =(browse-kill-ring-default-keybindings)= to your =~/.emacs=.
  Otherwise you can map =browse-kill-ring= to another key combination,
  for example =(global-set-key "\C-cy" 'browse-kill-ring)=.
Simple, no?

* HISTORY
Originally written by Colin Walters (Debian Developer, Emacs hacker, SELinux
hacker, and general Free Software Guru Extrordinaire). After that maintained
by [[https://github.com/todesschaf][Nick Hurley]]. Unfortunately he had to abandon emacs. Therefore this organisation
account is created at Github. Feel free to issue pull requests.
Current contibutors:
- [[https://github.com/monsanto][Christopher Monsanto]]
- [[https://github.com/T-J-Teru][Andrew]]
- [[https://github.com/To1ne][Toon Claes]]
