#!/bin/zsh

echo "clearing out live packs"
rm -rf ~/.emacs.d/packs/stable

echo "creating new live pack dir"
mkdir ~/.emacs.d/packs/stable

echo "copying content from dev packs"
cp -pRL ~/.emacs.d/packs/dev/* ~/.emacs.d/packs/stable/

echo "removing dev detritus"
rm -rf ~/.emacs.d/packs/stable/**/vendor
rm -rf ~/.emacs.d/packs/stable/**/.git*
rm -rf ~/.emacs.d/packs/stable/**/*.elc
