#!/bin/sh

echo "clearing out live packs"
find ~/.emacs.d/packs/stable \
     -maxdepth 1 \
     ! -name 'stable' \
     ! -name '.gitkeep' \
     -type d \
     -exec rm -Rf {} \;

echo "copying content from dev packs"
cp -pRL ~/.emacs.d/packs/dev/* ~/.emacs.d/packs/stable/

echo "removing dev detritus"
rm -rf ~/.emacs.d/packs/stable/**/vendor
rm -rf ~/.emacs.d/packs/stable/**/.git*
rm -rf ~/.emacs.d/packs/stable/**/*.elc
